spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/teamchat?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: qwert12345
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show-sql: true
        generate-ddl: true

  servlet:
    multipart:
      maxFileSize: 1000MB
      maxRequestSize: 1000MB
server:
  port: 8080